using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Vulpine.Core.Calc.Exceptions
{
    /// <summary>
    /// This is the base class for all exceptions generated by and
    /// pretaning to mathmatical opperations.
    /// </summary>
    public class MathematicsExcp : Exception
    {
        /// <summary>
        /// Creates a new exception with the given message.
        /// </summary>
        /// <param name="msg">A message explaning the nature and
        /// cause of the exception</param>
        public MathematicsExcp(string msg) : base(msg) { }

        /// <summary>
        /// Creates a new math exception. Sub-clases should provide
        /// a custom message by overriding the virtual Message property.
        /// </summary>
        public MathematicsExcp() : base() { }
    }
}
